

'Ouestions'
'-how python objects are innitialized.'
'-which method contructs the object in python'
'-what is the purporse of __new__ method and whats are the arguments need to pass to it.'




'Random cuts'
'recurrsion-- see if the same algo can be done using the recurrsion and why?'
'list iteration shortcuts'
'names have scope in python but values dont. Thats why values can be accessed accross the function call and manipulated like lists'
'when we take a slice of a list we get a new list'
'x += [] add another list in place(mutation), while x = x + [] creates new list object and assign it to x(rebinding)'
'slicing list do not raise IndexError even if the slicing index is out of range'
'mro (method resolution search order) is the search order in which a attribute is searched when accessed by obj.attribute or getattr(obj, attribute) or the super(type) call'
'cooperative multiple inheritance in python'
'isinstance and issubclass use cases'
'whats the magic of magic methods'
'the process of solving the MRO of a class is called linearization'
'The MRO calculation contraints are'
'- a class always precedes its parents'
'- multiple base classes followes the order of base class tuple'
'a namespace is a mapping from names to objects'
'scopes are defined statically but are used dynamically'
'scopes is the textual region of python program where the namespace is directly accessible (without any prefixing)'
'Truth value testing is used to find the bool of any object'
'z = x and y  -- if x is false then x else y'
'z = x or y --  if x is false then y else x'
'floating point arithmatic, its issues and limitations-'
'when we input a decimal fraction like var = 0.1 in python , python actually stores the approximated binary fracion value in the macine because there are many decmial fractions which cannot be exactly represented as binary fractions.'
' - this is similar to decimal fracion 1/3 which is 0.333333.... and infinite 3  '
' python sorting '

'python generator can only be iterated once and and same goes for the iterator'
'because the all values are not kept in memory at the same time because they are generated on the fly'
' a, b = b, a+b '
' - this expression is evaluated in two phases 1)tuple packing 2)sequence unpacking'

'how to simulate the list builtin methods'
'list builtin methods'
'dictionary builtin methods'
'methods on string object always returns a new string object. For list there are some methods which mutates the list in place'
'- like the sort, extend method '
'-list comprehension always creates a new list unaltering the oringinal list'
'simulate itertools methods as well as other builtin methods on core objects'
